alias c="clear"
alias eb="exec bash"
alias gf="git fetch"
alias gp="git pull"
alias gpx="git push"
alias gq="git add .; git commit -m 'quick commit'"
alias gqx="gq; git push"
alias gs="git status"
alias gsa="git stash apply"
alias gsx="git stash -u"
alias nd="npm run dev"
alias nb="npm run build"
alias nbx="nb; gqx"

