import "./Vars.css";
import "./Fonts.css";
import "./Universal.css";
import "./AreaLayers.css";
import "./ControlArea.css";
import "./GameArea.css";
import "./ScoreArea.css";
import "./TitleArea.css";
import "./Animations.css";
